# Generated by Django 5.2.5 on 2025-08-08 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('contrasena', models.CharField(max_length=42)),
                ('correo_electronico', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('numero_documento', models.CharField(max_length=15)),
                ('numero_telefonico', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=70)),
                ('direccion', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=35)),
                ('descripcion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nit_proveedor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('n_documento', models.IntegerField()),
                ('n_tel', models.IntegerField()),
                ('correo', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=40)),
                ('especialidad', models.CharField(max_length=40)),
                ('tipo_tecnico', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion_venta', models.CharField(max_length=50)),
                ('terminos_y_condiciones', models.CharField(max_length=250)),
                ('nit_digisoft', models.CharField(max_length=50)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Garantias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facturacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.facturacion')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=35)),
                ('clave', models.CharField(max_length=35)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.cliente')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.marca')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id_ordenServicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_orden', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('finalizado', 'Finalizado')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.cliente')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.tecnico')),
            ],
        ),
        migrations.AddField(
            model_name='facturacion',
            name='orden_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.ordenservicio'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=35)),
                ('modelo_producto', models.CharField(max_length=40)),
                ('cantidad', models.IntegerField()),
                ('valor_producto', models.CharField(max_length=45)),
                ('diseno', models.CharField(max_length=40)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.marca')),
            ],
        ),
        migrations.CreateModel(
            name='ComprasMercancia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_compras', models.IntegerField()),
                ('fecha_compra', models.DateField()),
                ('precio_compra', models.CharField(max_length=50)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.administrador')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioTecnico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipo', models.CharField(max_length=100)),
                ('descripcion_falla', models.TextField()),
                ('fecha_ingreso', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.producto')),
            ],
        ),
        migrations.AddField(
            model_name='facturacion',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apl.venta'),
        ),
    ]
