# Generated by Django 5.2.4 on 2025-08-01 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='marca_id',
            field=models.ForeignKey(blank=True, db_column='marca_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apl.marca'),
        ),
    ]
