# Generated by Django 5.2.4 on 2025-08-05 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='color',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='marca',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color_producto',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca_id',
            field=models.ForeignKey(blank=True, db_column='marca_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apl.marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
