# Generated by Django 5.2.5 on 2025-08-13 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0003_alter_venta_cliente_alter_venta_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apl.administrador'),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='descripcion_venta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='orden_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apl.ordenservicio'),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apl.venta'),
        ),
    ]
